<canvas class="myCanvas unselectable" id="layer1" width="750" height="600" style=" position:absolute; visibility: visible;  z-index: 0; solid #c3c3c3;">Your browser does not support the canvas element.</canvas>

<canvas class="myCanvas unselectable" id="layer2" width="750" height="600" style="position:absolute; visibility: visible;  z-index: 1; solid #c3c3c3;">Your browser does not support the canvas element.</canvas>


<audio id="music">
  <source src="/sound/music.mp3" type="audio/mp3" />
  Your browser does not support the audio tag.
</audio>


<audio id="sound1" class="sfx" src="/sound/sound1.mp3" >
  <source src="/sound/sound1.mp3" type="audio/mp3" />
</audio>
<audio id="sound2" class="sfx" src="/sound/sound2.mp3">
  <source src="/sound/sound2.mp3" type="audio/mp3" />
</audio>
<audio id="sound3" class="sfx" src="/sound/sound3.mp3">
  <source src="/sound/sound3.mp3" type="audio/mp3" />
</audio> 
<audio id="sound4" class="sfx" src="/sound/sound4.mp3">
  <source src="/sound/sound4.mp3" type="audio/mp3" />
</audio> 
<audio id="sound5" class="sfx" src="/sound/sound5.mp3">
  <source src="/sound/sound5.mp3" type="audio/mp3" />
</audio> 



<audio id="sound6" class="sfx" src="/sound/pijanec1.mp3">
  <source src="/sound/pijanec1.mp3" type="audio/mp3" />
</audio> 


<audio id="sound7" class="sfx" src="/sound/pijanci1.mp3">
  <source src="/sound/pijanci1.mp3" type="audio/mp3" />
</audio> 


<audio id="sound8" class="sfx" src="/sound/button1.mp3">
  <source src="/sound/button1.mp3" type="audio/mp3" />
</audio> 

